version: '3.3'
services:
  structurizr-onpremises:
    image: structurizr/onpremises
    container_name: structurizr-onpremises
    ports:
      - 8081:8080
    volumes:
        - ./onpremises:/usr/local/structurizr:z


